trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

# Install Terraform
- script: |
    echo "Installing Terraform..."
    TERRAFORM_VERSION="1.15.8"

    wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

    unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip

    sudo mv terraform /usr/local/bin/

    terraform version
  displayName: 'Install Terraform'


# Terraform Format Check
- script: |
    terraform fmt -check -recursive
  displayName: 'Terraform Format Check'


# Azure Login + Terraform Init
- task: AzureCLI@2
  displayName: 'Azure Login + Terraform Init'
  inputs:
    azureSubscription: 'ado-terraform-azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    addSpnToEnvironment: true
    inlineScript: |

      echo "Azure authentication successful"

      az account show

      echo "Setting Terraform OIDC authentication..."

      export ARM_USE_OIDC=true
      export ARM_CLIENT_ID="$servicePrincipalId"
      export ARM_OIDC_TOKEN="$idToken"
      export ARM_TENANT_ID="$tenantId"

      echo "Running Terraform Init..."

      cd "$(System.DefaultWorkingDirectory)/environments/dev"

      terraform init